# 1. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d
# --this command will start the containers in detached mode without rebuilding the images (if they already exist)
#
#2. docker-compose -p microservices-comp3095-ecommerce -f docker-compose.yml up -d --build
# -- This command forces the rebuild of images, even if the image already exist,before starting the containers
#
version : '3.9'

services:

  product-service:
    image: product-service
    ports:
      - "8084:8084"  #external:internal  when communicating from host machine:
    build:
      context: ./product-service    #directory where the Dockerfile resides
      dockerfile: ./Dockerfile    #specify dockerfile for use to build image
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - spring

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db    #locally creating a data folder and subfolders
        # writing virtually logically in data/db but relaistically in mongo/products
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        #Initialize mongodb with data from this script
        #mapping host to the containerized env  : read and only
    #restart: unless-stopped
    #command: mongod --auth
    networks:
      - spring


  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express-service
    depends_on:
      - mongodb
    networks:
      - spring

        #optional volumes
volumes:
  mongo-db:
    driver: local

networks:
    spring:
      driver: bridge
