# for docker to read and execute the mongo-init.js file, the database must NOT already exist
#that is init.js file is only executed the one time, on newly initialized database
version : '3.9'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db    #locally creating a data folder and subfolders
      # writing virtually logically in data/db but relaistically in mongo/products
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        #Initialize mongodb with data from this script
      #mapping host to the containerized env  : read and only
    #restart: unless-stopped
    command: mongod -auth
    networks:
      - spring


  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb   #connect mongo-express to the mongodb container by name
    container_name: mongo-express-service
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - spring

      #optional volumes
volumes:
  mongo-db:
    driver: local

networks:
  spring:
    driver: bridge
