#docker-compose -p postgres-single -f docker-compose.yml up -d
# docker-compose -p local-docker-file/postgres/postgres-single -f docker-compose.yml up -d
version : '3.9'

services:

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    container_name: postgres-inventory
    environment:
      - POSTGRES_USER=rootadmin
      - POSTGRES_PASSWORD=password
      #- POSTGRES_DB=inventory-service
      #- PGDATA: /data/postgres

    volumes:
      - ./data/inventory:/var/lib/postgresql/data
      - ./init/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql

 #for order service not want it to be running while doin inventory service
 # postgres:
  #  image: postgres
  #  ports:
   #   - "5432:5432"
    #container_name: postgres-single
    #environment:
  #    - POSTGRES_USER=rootadmin
   #   - POSTGRES_PASSWORD=password
    #volumes:
     #   - ./data/order:/var/lib/postgresql/data
      #  - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-inventory
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
