#docker-compose -p postgres-single -f docker-compose.yml up -d

version : '3.9'

services:

  Order-service:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-order
    environment:
      - POSTGRES_USER=rootadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB= order-service
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-single
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql