#docker-compose -p postgres-single -f docker-compose.yml up -d
# docker-compose -p local-docker-file/postgres/postgres-single -f docker-compose.yml up -d
#docker-compose -p postgres-services -f local-docker-file/postgres/docker-compose-multiple.yml up -d --build
version : '3.9'

services:

  Inventory-service:
    image: postgres
    ports:
      - "5434:5432"
    container_name: postgres-inventory
    environment:
      - POSTGRES_USER=rootadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-service
      #- PGDATA: /data/postgres
    volumes:
      - ./data/inventory:/var/lib/postgresql/data
      - ./init/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

 #for order service not want it to be running while doin inventory service
  Order-service:
    image: postgres
    ports:
      - "5433:5432"
    container_name: postgres-order
    environment:
      - POSTGRES_USER=rootadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-service
    volumes:
        - ./data/order:/var/lib/postgresql/data
        - ./init/order/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - spring

networks:
  spring: